# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Crazy Iris's blog
subtitle: To share to learn
description: A beginner , A learner
keywords: 前端博客,JavaScript,html5,css3,Jquery,NodeJs,Ubuntu,hexo
author: Iris
language: zh-CN
timezone: UTC

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://jeffrey126.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -update
archive_generator:
  per_page: 0
  yearly: true
  monthly: false
tag_generator:
  per_page: 10

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

theme_config:

  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini


# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: git@github.com:jeffrey126/jeffrey126.github.io.git
  branch: gh-pages

# hexo-renderer-markdown-it-plus config
## Docs: https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus
markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer:
    quotes: “”‘’
    pre_class: highlight
    plugins:
        - plugin:
            name: markdown-it-mark
            enable: true

# word count
# Dependencies: https://github.com/theme-next/hexo-symbols-count-time
# 字数统计插件 npm i hexo-symbols-count-time
symbols_count_time:
  symbols: true # 文章字数统计
  time: true # 文章时长统计
  total_symbols: true # 全局字数统计
  total_time: true # 全局时长统计
  exclude_codeblock: false  # 排除代码字数统计


search:
  path: search.xml
  field: post
  format: html
  limit: 10000


aplayer:
  meting: false                                # Meting support, default: false

# Extensions
plugins: hexo-generator-sitemap

sitemap:
path: sitemap.xml

# Live2D
## https://github.com/xiazeyu/live2d-widget.js
## https://l2dwidget.js.org/docs/class/src/index.js~L2Dwidget.html#instance-method-init
live2d:
  model:
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
    use: live2d-widget-model-z16 // 下载的动画模型名称
  display:
    superSample: 2
    width: 80
    height: 160
    position: right // 模型在网页显示位置
    hOffset: 20
    vOffset: 50
  mobile:
    show: true  // 移动设备是否显示
    scale: 0.5
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.2

#aplayer:
#  meting: true                                  # Meting support, default: false


#leancloud_visitors:
#  enable: true
#  appid: A8ARnWNOpqSq7M0C1AcfQjGo-gzGzoHsz
#  appkey: U5qcKsPykQupbUPAVwoKPPe0



